#!/bin/bash

# You may need to `usermod -a -G input $yourself` for the following to work

exec deno run --unstable-net --check=all --allow-all wbbconnector.ts v2 \
	'--target=osc+udp://192.168.9.9:9901;debug=on/wbb' \
	'00:21:BD:D1:5C:A9' \
	'58:BD:A3:AC:20:AD' \
	"$@"
