#!/bin/bash

# You may need to `usermod -a -G input $yourself` for the following to work

exec deno run --check=all --allow-all wbbconnector.ts v2 \
	'00:21:BD:D1:5C:A9' \
	'58:BD:A3:AC:20:AD' \
	"$@"
